# --- Этап 1: Сборка (Build) ---
FROM node:20-alpine as build

WORKDIR /app

# Копируем сначала файлы зависимостей (для кэширования слоев)
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь исходный код
COPY . .

# Собираем проект (Vite создаст папку dist/)
RUN npm run build

# --- Этап 2: Раздача (Serve) ---ping summarizer.internal
FROM nginx:alpine

# Копируем собранные файлы из этапа build
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем наш конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]